package org.digidoc4j.exceptions;

public class LotlTrustStoreNotFoundException extends DigiDoc4JException {

  public LotlTrustStoreNotFoundException(String message, Throwable cause) {
    super(message, cause);
  }

}
